name: ui_ex
description: 'ui_ex is a solution that provides chain programming, which can easily solve the addition and removal of controls.'
version: 1.0.2
homepage: 'https://github.com/flutter-dd/ui_ex.git'
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
