name: ui_ex
description: flutter about ui extension
version: 0.0.4
homepage: https://github.com/flutter-dd/ui_ex.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.0.4
  flutter_math_fork: ^0.3.3+1
  skeleton_text: ^3.0.0
  tuple: ^2.0.0
  line_icons: ^2.0.1
  path_drawing: ^0.5.1
  vector_math: ^2.1.0
  flutter_markdown: ^0.6.8
  markdown: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
