part of ui_ex;

extension ToggleButtonsEx<T extends Widget> on List<T> {
  ToggleButtons toggleButtons(
    List<bool> isSelected, {
    Key? key,
    void Function(int)? onPressed,
    MouseCursor? mouseCursor,
    TextStyle? textStyle,
    BoxConstraints? constraints,
    Color? color,
    Color? selectedColor,
    Color? disabledColor,
    Color? fillColor,
    Color? focusColor,
    Color? highlightColor,
    Color? hoverColor,
    Color? splashColor,
    List<FocusNode>? focusNodes,
    bool renderBorder = true,
    Color? borderColor,
    Color? selectedBorderColor,
    Color? disabledBorderColor,
    BorderRadius? borderRadius,
    double? borderWidth,
    Axis direction = Axis.horizontal,
    VerticalDirection verticalDirection = VerticalDirection.down,
  }) =>
      ToggleButtons(
        children: this,
        isSelected: isSelected,
        key: key,
        onPressed: onPressed,
        mouseCursor: mouseCursor,
        textStyle: textStyle,
        constraints: constraints,
        color: color,
        selectedColor: selectedColor,
        selectedBorderColor: selectedBorderColor,
        disabledColor: disabledColor,
        disabledBorderColor: disabledBorderColor,
        fillColor: fillColor,
        focusColor: focusColor,
        highlightColor: highlightColor,
        hoverColor: hoverColor,
        splashColor: splashColor,
        focusNodes: focusNodes,
        renderBorder: renderBorder,
        borderColor: borderColor,
        borderRadius: borderRadius,
        borderWidth: borderWidth,
        direction: direction,
        verticalDirection: verticalDirection,
      );
}
