part of ui_ex;

/// 材质平钮
/// FlatButton
extension MaterialFlatButtonEx<T extends Widget?> on T {
  /// FlatButton
  // FlatButton flatButton({
  //   Key? key,
  //   required void Function()? onPressed,
  //   void Function()? onLongPress,
  //   void Function(bool)? onHighlightChanged,
  //   MouseCursor? mouseCursor,
  //   ButtonTextTheme? textTheme,
  //   Color? textColor,
  //   Color? disabledTextColor,
  //   Color? color,
  //   Color? disabledColor,
  //   Color? focusColor,
  //   Color? hoverColor,
  //   Color? highlightColor,
  //   Color? splashColor,
  //   Brightness? colorBrightness,
  //   EdgeInsetsGeometry? padding,
  //   VisualDensity? visualDensity,
  //   ShapeBorder? shape,
  //   Clip clipBehavior = Clip.none,
  //   FocusNode? focusNode,
  //   bool autofocus = false,
  //   MaterialTapTargetSize? materialTapTargetSize,
  //   required Widget child,
  //   double? height,
  //   double? minWidth,
  // }) =>
  //     FlatButton(
  //       key: key,
  //       onPressed: onPressed,
  //       onLongPress: onLongPress,
  //       onHighlightChanged: onHighlightChanged,
  //       mouseCursor: mouseCursor,
  //       textTheme: textTheme,
  //       textColor: textColor,
  //       disabledTextColor: disabledTextColor,
  //       color: color,
  //       disabledColor: disabledColor,
  //       focusColor: focusColor,
  //       hoverColor: hoverColor,
  //       highlightColor: highlightColor,
  //       splashColor: splashColor,
  //       colorBrightness: colorBrightness,
  //       padding: padding,
  //       visualDensity: visualDensity,
  //       shape: shape,
  //       clipBehavior: clipBehavior,
  //       focusNode: focusNode,
  //       autofocus: autofocus,
  //       materialTapTargetSize: materialTapTargetSize,
  //       child: this ?? Container(),
  //       height: height,
  //       minWidth: minWidth,
  //     );
}
